"""replace articles with activities and add in_charge relation

Revision ID: 60e687210b41
Revises: 4d27be7f9477
Create Date: 2026-06-06 22:17:15.292949

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision = '60e687210b41'
down_revision = '4d27be7f9477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('activity_type', sa.String(length=128), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('venue', sa.String(length=256), nullable=True),
    sa.Column('reference_link', sa.String(length=256), nullable=True),
    sa.Column('status', sa.Enum('planned', 'in_progress', 'on_hold', 'under_review', 'accepted', 'rejected', 'completed', 'cancelled', name='activitystatus'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('completed_at', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activities_lab_id'), ['lab_id'], unique=False)

    op.create_table('activity_in_charge',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'activity_id')
    )
    op.create_table('activity_participants',
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'activity_id')
    )
    op.drop_table('article_authors')
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_articles_lab_id'))

    op.drop_table("articles")
    with op.batch_alter_table("lab_memberships", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_memberships_reports_to_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_memberships_reports_to_id"),
            "members",
            ["reports_to_id"],
            ["id"],
            ondelete="SET NULL",
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lab_memberships", schema=None) as batch_op:
        batch_op.drop_constraint(
            batch_op.f("fk_memberships_reports_to_id"), type_="foreignkey"
        )
        batch_op.create_foreign_key(
            batch_op.f("fk_memberships_reports_to_id"), "members", ["reports_to_id"], ["id"]
        )

    op.create_table('articles',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=256), nullable=False),
    sa.Column('abstract', sa.TEXT(), nullable=True),
    sa.Column('doi', sa.VARCHAR(length=128), nullable=True),
    sa.Column('published_at', sa.DATE(), nullable=True),
    sa.Column('lab_id', sa.INTEGER(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('conference', sa.VARCHAR(length=256), nullable=True),
    sa.Column('status', sa.VARCHAR(length=12), server_default=sa.text("'in_progress'"), nullable=False),
    sa.Column('submission_deadline', sa.DATE(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('in_charge', sqlite.JSON(), server_default=sa.text("'[]'"), nullable=False),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doi')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_articles_lab_id'), ['lab_id'], unique=False)

    op.create_table('article_authors',
    sa.Column('member_id', sa.INTEGER(), nullable=False),
    sa.Column('article_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'article_id')
    )
    op.drop_table('activity_participants')
    op.drop_table('activity_in_charge')
    with op.batch_alter_table('activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_activities_lab_id'))

    op.drop_table('activities')
    # ### end Alembic commands ###
