"""add member profile links, lab leave and invite tokens

Revision ID: be1ceaaefba9
Revises: 91852978b72c
Create Date: 2026-08-21 08:09:56.518851

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'be1ceaaefba9'
down_revision = '91852978b72c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('lab_id', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used_by_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lab_id'], ['laboratories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['used_by_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invite_tokens_token'), ['token'], unique=True)

    with op.batch_alter_table('lab_memberships', schema=None) as batch_op:
        batch_op.add_column(sa.Column('left_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lattes_url', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('orcid', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('github_url', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('members', schema=None) as batch_op:
        batch_op.drop_column('github_url')
        batch_op.drop_column('orcid')
        batch_op.drop_column('lattes_url')

    with op.batch_alter_table('lab_memberships', schema=None) as batch_op:
        batch_op.drop_column('left_at')

    with op.batch_alter_table('invite_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invite_tokens_token'))

    op.drop_table('invite_tokens')
    # ### end Alembic commands ###
